### ISSUE TITLE
Config::MVP::Reader::INI fails test on Windows

### ISSUE THREAD

**Issue by Corion** [rjbs/Config-MVP-Reader-INI#6]
The tests for Config::MVP::Reader::INI assume that Config::INI will read a newline-delimited file on Windows without error. This is wrong as the Config::MVP::Reader::INI test fails with

    Syntax error at line 2: '1
    ' at lib/Config/MVP/Reader/INI.pm line 25.

The proper fix is to reset the encoding in the call to

    ->read_file

to

    $reader->read_file({ binmode => ':raw' }, $location);

or maybe to

    $reader->read_file({ binmode => ':raw:encoding(UTF-8)' }, $location);

This is currently the first blocker that prevents Dist::Zilla from installing on Windows.

**Comment by Corion** [comment]
t/000-report-versions-tiny.t .. #
    #
    # Generated by Dist::Zilla::Plugin::ReportVersions::Tiny v1.10
    # perl: 5.016003 (wanted any version) on MSWin32 from C:\strawberry-perl-5.16.3.1-x64\perl\bin\perl.exe
    #
    # Config::INI::Reader                           => 0.021      (want any version)
    # Config::MVP                                   => 2.200006   (want 2)
    # Config::MVP::Reader                           => 2.200006   (want any version)
    # Config::MVP::Reader::Findable::ByExtension    => 2.200006   (want any version)
    # ExtUtils::MakeMaker                           => 7.02       (want 6.30)
    # Moose                                         => 2.0604     (want any version)
    # Test::More                                    => 1.001008   (want 0.96)
    # lib                                           => 0.63       (want any version)
    # parent                                        => 0.225      (want any version)
    # strict                                        => 1.07       (want any version)
    # warnings                                      => 1.13       (want any version)
    #

**Comment by Corion** [comment]
My proposed fix then breaks Dist::Zilla with lots of encoding mismatches. But I'll leave that up to you how to make Dist::Zilla work on Windows.

**Comment by rjbs** [comment]
This has been fixed for some time now, I just neglected to close this bug.  (DZ installs on Win32.)
