### ISSUE TITLE
Missing dependencies for latest release

### ISSUE THREAD

**Issue by glasswalk3r** [rjbs/Config-MVP-Reader-INI#7]
Hi!

I got some errors from a CPAN smoker that I have configured while trying to install Config-MVP-Reader-INI. These were the missing modules that I got errors from the tests:

- MooseX::OneArgNew
- Role::HasMessage
- Role::Identifiable::HasIdent
- Throwable
- Tie::IxHash

The declared dependencies on the Makefile.PL were already installed, but only by installing those modules manually I was able to pass all the tests.

My best regards,

Alceu

**Comment by rjbs** [comment]
Config-MVP-Reader-INI does not require MooseX::OneArgNew, Role::HasMessage, etc.  On the other hand, Config::MVP does.  You should not have been able to install Config::MVP without having those things installed.  I'm going to close this ticket on the theory that "something was wack with your CPAN install."  If you have any evidence that there is a fault in my dependencies somewhere, though, please let me know!
